services:
  database:
    image: mongo
    ports:
      - "27018:27017"
    container_name: mongo_medi-clients
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_medi-clients:/data/db
volumes:
  mongodb_medi-clients:
